require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExpressPricesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ExpressPrice. As you add validations to ExpressPrice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExpressPricesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all express_prices as @express_prices" do
      express_price = ExpressPrice.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:express_prices)).to eq([express_price])
    end
  end

  describe "GET #show" do
    it "assigns the requested express_price as @express_price" do
      express_price = ExpressPrice.create! valid_attributes
      get :show, params: {id: express_price.to_param}, session: valid_session
      expect(assigns(:express_price)).to eq(express_price)
    end
  end

  describe "GET #new" do
    it "assigns a new express_price as @express_price" do
      get :new, params: {}, session: valid_session
      expect(assigns(:express_price)).to be_a_new(ExpressPrice)
    end
  end

  describe "GET #edit" do
    it "assigns the requested express_price as @express_price" do
      express_price = ExpressPrice.create! valid_attributes
      get :edit, params: {id: express_price.to_param}, session: valid_session
      expect(assigns(:express_price)).to eq(express_price)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ExpressPrice" do
        expect {
          post :create, params: {express_price: valid_attributes}, session: valid_session
        }.to change(ExpressPrice, :count).by(1)
      end

      it "assigns a newly created express_price as @express_price" do
        post :create, params: {express_price: valid_attributes}, session: valid_session
        expect(assigns(:express_price)).to be_a(ExpressPrice)
        expect(assigns(:express_price)).to be_persisted
      end

      it "redirects to the created express_price" do
        post :create, params: {express_price: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ExpressPrice.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved express_price as @express_price" do
        post :create, params: {express_price: invalid_attributes}, session: valid_session
        expect(assigns(:express_price)).to be_a_new(ExpressPrice)
      end

      it "re-renders the 'new' template" do
        post :create, params: {express_price: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested express_price" do
        express_price = ExpressPrice.create! valid_attributes
        put :update, params: {id: express_price.to_param, express_price: new_attributes}, session: valid_session
        express_price.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested express_price as @express_price" do
        express_price = ExpressPrice.create! valid_attributes
        put :update, params: {id: express_price.to_param, express_price: valid_attributes}, session: valid_session
        expect(assigns(:express_price)).to eq(express_price)
      end

      it "redirects to the express_price" do
        express_price = ExpressPrice.create! valid_attributes
        put :update, params: {id: express_price.to_param, express_price: valid_attributes}, session: valid_session
        expect(response).to redirect_to(express_price)
      end
    end

    context "with invalid params" do
      it "assigns the express_price as @express_price" do
        express_price = ExpressPrice.create! valid_attributes
        put :update, params: {id: express_price.to_param, express_price: invalid_attributes}, session: valid_session
        expect(assigns(:express_price)).to eq(express_price)
      end

      it "re-renders the 'edit' template" do
        express_price = ExpressPrice.create! valid_attributes
        put :update, params: {id: express_price.to_param, express_price: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested express_price" do
      express_price = ExpressPrice.create! valid_attributes
      expect {
        delete :destroy, params: {id: express_price.to_param}, session: valid_session
      }.to change(ExpressPrice, :count).by(-1)
    end

    it "redirects to the express_prices list" do
      express_price = ExpressPrice.create! valid_attributes
      delete :destroy, params: {id: express_price.to_param}, session: valid_session
      expect(response).to redirect_to(express_prices_url)
    end
  end

end
